# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68fab1d55b963fa24575f2795a182714"
name = "awesome-discount"
handle = "awesome-discount"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
api_version = "2024-10"

